### ISSUE TITLE
If heic does not include 4 images it's impossible to create a theme

### ISSUE THREAD

**Issue by Dustmix** [gdstewart/ddw-theme-creator#6]
If i try to convert a heic file that doesn't include more than 4 pictures, it's impossible to create a theme as an image is required for day, night, sunrise and sunset spots.
![image](https://user-images.githubusercontent.com/43365173/98389494-6c39c880-2054-11eb-9431-eefd7b09467a.png)

**Comment by gdstewart** [comment]
This was intended because of the way WinDynamicDesktop works, but you're right that it doesn't really make sense. I'll change it to make it so you need at least a day and a night image, and if sunrise or sunset images are not provided the program will automatically assume they are the same as the day and night images.

**Comment by gdstewart** [comment]
Should work for you now
